pipeline {
    agent any

    environment {
        IMAGE_NAME = 'nest-cicd-deployment-test-app'
        KUBE_NAMESPACE = 'default'
        DEPLOYMENT_NAME = 'nestjs-cicd-app'
        REGISTRY_HOST = 'localhost'  // Update to access the local registry from Kubernetes
        REGISTRY_PORT = '9002'  // The port of the local Docker registry
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/prasad-potdar/nestjs-docker-cicd-deployment-test.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    withEnv(["PATH+DOCKER=/usr/local/bin"]) {
                        // Build the Docker image and tag it
                        sh "docker build -t ${IMAGE_NAME}:${env.BUILD_NUMBER} -f deployment/Dockerfile ."
                        sh "docker tag ${IMAGE_NAME}:${env.BUILD_NUMBER} ${IMAGE_NAME}:latest"
                    }
                }
            }
        }

        stage('Push Docker Image to Local Registry') {
            steps {
                script {
                    // Push the image to the local registry
                    sh "docker tag ${IMAGE_NAME}:latest ${REGISTRY_HOST}:${REGISTRY_PORT}/${IMAGE_NAME}:latest"
                    sh "docker push ${REGISTRY_HOST}:${REGISTRY_PORT}/${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Ensure the Kubernetes deployment file is configured correctly to pull from the local registry
                    sh """
                    kubectl apply -f deployment/k8s/deployment.yaml
                    kubectl apply -f deployment/k8s/service.yaml
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }

        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Deployment Failed'
        }

        unstable {
            echo 'Deployment Unstable'
        }

        changed {
            echo 'Deployment Changed'
        }
    }
}
