apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nest-cicd-deployment-test-app
          image: prasadmpotdar/nestjs-app/nest-cicd-deployment-test-app:latest
          ports:
            - containerPort: 3000