apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
spec:
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 80        # Expose on this port
      targetPort: 3000 # Container's internal port
      nodePort: 30080  # Assign a port on the node for external access
  type: NodePort  # Expose the service via NodePort
