apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
spec:
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 80           # Port on the service
      targetPort: 3000    # Port on the container
      nodePort: 30080     # The specific NodePort you want to expose (optional)
  type: NodePort          # Change to NodePort instead of LoadBalancer
