apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
spec:
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 80        # Exposed port on the service
      targetPort: 3000 # Container's internal port
  type: LoadBalancer # Minikube will simulate a LoadBalancer
